site_name: Prefect 1.0
site_url: https://docs.prefect.io
repo_url: https://github.com/PrefectHQ/prefect
edit_uri:
extra_css:
    - stylesheets/theme.css
    - stylesheets/admonitions.css
    - stylesheets/api_ref.css
    - stylesheets/rest_ref.css
    - stylesheets/syntax_highlights.css
    - stylesheets/termynal.css
    - stylesheets/extra.css
extra_javascript:
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
theme:
    name: material
    custom_dir: overrides
    favicon: /img/favicon.ico
    features:
        - toc.integrate
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.instant
    font:
        text: Inter
        code: Source Code Pro
    icon:
        repo: fontawesome/brands/github
    logo: img/assets/logomark-light.svg
    palette:
        primary: blue
        accent: blue
    custom_dir: docs/overrides
plugins:
    autorefs: {}
    mkdocstrings:
        custom_templates: docs/templates
        handlers:
            python:
                rendering:
                    show_root_heading: True
                    show_object_full_path: False
                    show_category_heading: False
                    show_bases: False
                    heading_level: 1
        watch:
            - src/prefect/
    search: {}
nav:
    - Prefect 1.0: index.md
    - Core:
        - Overview: core/README.md
        - About Prefect:
            - Why Prefect?: core/about_prefect/why-prefect.md
            - Why not Airflow?: core/about_prefect/why-not-airflow.md
            - Thinking Prefectly: core/about_prefect/thinking-prefectly.md
            - Next Steps: core/about_prefect/next-steps.md
        - Getting Started:
            - core/getting_started/quick-start.md
            - core/getting_started/install.md
            - core/getting_started/basic-core-flow.md
            - core/getting_started/more-resources.md
        - ETL Tutorial:
            - core/tutorial/01-etl-before-prefect.md
            - core/tutorial/02-etl-flow.md
            - core/tutorial/03-parameterized-flow.md
            - core/tutorial/04-handling-failure.md
            - core/tutorial/05-running-on-a-schedule.md
            - core/tutorial/06-parallel-execution.md
            - core/tutorial/07-next-steps.md
        - Core Concepts: 
            - core/concepts/tasks.md
            - core/concepts/flows.md
            - core/concepts/parameters.md
            - core/concepts/states.md
            - core/concepts/engine.md
            - core/concepts/execution.md
            - core/concepts/logging.md
            - core/concepts/mapping.md
            - core/concepts/notifications.md
            - core/concepts/persistence.md
            - core/concepts/results.md
            - core/concepts/templating.md
            - core/concepts/schedules.md
            - core/concepts/secrets.md
            - core/concepts/configuration.md
            - core/concepts/best-practices.md
            - core/concepts/common-pitfalls.md
    - Orchestration: orchestration/README.md