site_name: Prefect 1.0
site_url: https://docs.prefect.io
repo_url: https://github.com/PrefectHQ/prefect
edit_uri:
extra_css:
    - stylesheets/theme.css
    - stylesheets/admonitions.css
    - stylesheets/api_ref.css
    - stylesheets/rest_ref.css
    - stylesheets/syntax_highlights.css
    - stylesheets/termynal.css
    - stylesheets/extra.css
extra_javascript:
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
theme:
    name: material
    custom_dir: overrides
    favicon: /img/favicon.ico
    features:
        - toc.integrate
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.instant
    font:
        text: Inter
        code: Source Code Pro
    icon:
        repo: fontawesome/brands/github
    logo: img/assets/logomark-light.svg
    palette:
        primary: blue
        accent: blue
    custom_dir: docs/overrides
plugins:
    autorefs: {}
    mkdocstrings:
        custom_templates: docs/templates
        handlers:
            python:
                rendering:
                    show_root_heading: True
                    show_object_full_path: False
                    show_category_heading: False
                    show_bases: False
                    heading_level: 1
        watch:
            - src/prefect/
    search: {}
nav:
    - Prefect 1.0: index.md
    - Core:
        - Overview: core/README.md
        - About Prefect:
            - Why Prefect?: core/about_prefect/why-prefect.md
            - Why not Airflow?: core/about_prefect/why-not-airflow.md
            - Thinking Prefectly: core/about_prefect/thinking-prefectly.md
            - Next Steps: core/about_prefect/next-steps.md
        - Getting Started:
            - core/getting_started/quick-start.md
            - core/getting_started/install.md
            - core/getting_started/basic-core-flow.md
            - core/getting_started/more-resources.md
        - ETL Tutorial:
            - core/tutorial/01-etl-before-prefect.md
            - core/tutorial/02-etl-flow.md
            - core/tutorial/03-parameterized-flow.md
            - core/tutorial/04-handling-failure.md
            - core/tutorial/05-running-on-a-schedule.md
            - core/tutorial/06-parallel-execution.md
            - core/tutorial/07-next-steps.md
        - Core Concepts: 
            - core/concepts/tasks.md
            - core/concepts/flows.md
            - core/concepts/parameters.md
            - core/concepts/states.md
            - core/concepts/engine.md
            - core/concepts/execution.md
            - core/concepts/logging.md
            - core/concepts/mapping.md
            - core/concepts/notifications.md
            - core/concepts/persistence.md
            - core/concepts/results.md
            - core/concepts/templating.md
            - core/concepts/schedules.md
            - core/concepts/secrets.md
            - core/concepts/configuration.md
            - core/concepts/best-practices.md
            - core/concepts/common-pitfalls.md
        - Advanced Tutorials:
            - Contents: core/advanced_tutorials/README.md
            - core/advanced_tutorials/advanced-mapping.md
            - core/advanced_tutorials/calculator.md
            - core/advanced_tutorials/custom-logs.md
            - core/advanced_tutorials/dask-cluster.md
            - core/advanced_tutorials/etl.md
            - core/advanced_tutorials/local-debugging.md
            - core/advanced_tutorials/slack-notifications.md
            - core/advanced_tutorials/task-guide.md
            - core/advanced_tutorials/task-looping.md
            - core/advanced_tutorials/using-results.md
            - core/advanced_tutorials/visualization.md
        - Examples:
            - core/examples/overview.md
            - core/examples/parameters.md
            - core/examples/conditional.md
            - core/examples/mapping.md
        - PINs:
            - Contents: core/PINs/README.md
            - core/PINs/PIN-01-Introduce-PINs.md
            - core/PINs/PIN-02-Result-Handlers.md
            - core/PINs/PIN-03-Agent-Environment.md
            - core/PINs/PIN-04-Result-Objects.md
            - core/PINs/PIN-05-Combining-Tasks.md
            - core/PINs/PIN-06-Remove-Constant-Tasks.md
            - core/PINs/PIN-07-Storage-Execution.md
            - core/PINs/PIN-08-Listener-Flows.md
            - core/PINs/PIN-09-CLI.md
            - core/PINs/PIN-10-Schedules.md
            - core/PINs/PIN-11-Task-Loops.md
            - core/PINs/PIN-12-Environment-Callbacks.md
            - core/PINs/PIN-13-Universal-Deploy.md
            - core/PINs/PIN-14-Listener-Flows-2.md
            - core/PINs/PIN-15-Skip-as-Finished-and-Conditionals.md
            - core/PINs/PIN-16-Results-and-Targets.md
        - Development:
            - core/development/overview.md
            - core/development/style.md
            - core/development/documentation.md
            - core/development/tests.md
            - core/development/contributing.md
            - core/development/release-checklist.md
            - core/development/sprints.md
        - Idioms:
            - Overview: core/idioms/idioms.md
            - core/idioms/notifications.md
            - core/idioms/secrets.md
            - core/idioms/script-based.md
            - core/idioms/testing-flows.md
            - core/idioms/task-run-names.md
            - core/idioms/conditional.md
            - core/idioms/mapping.md
            - core/idioms/parallel.md
            - core/idioms/targets.md
            - core/idioms/logging.md
            - core/idioms/flow-to-flow.md
            - core/idioms/resource-manager.md
            - core/idioms/piping.md
            - core/idioms/task-results.md
            - core/idioms/pause-for-approval.md
        - FAQ: core/faq.md
        - core/community.md
        - core/code_of_conduct.md
    - Orchestration: 
        - Overview: orchestration/README.md
        - Getting Started:
            - orchestration/getting-started/quick-start.md
            - orchestration/getting-started/install.md
            - orchestration/getting-started/basic-core-flow.md
            - orchestration/getting-started/set-up.md
            - orchestration/getting-started/registering-and-running-a-flow.md
            - orchestration/getting-started/next-steps.md
            - orchestration/getting-started/flow-configs.md
            - orchestration/getting-started/more-resources.md
        - Concepts:
            - orchestration/concepts/api.md
            - orchestration/concepts/api_keys.md
            - orchestration/concepts/cli.md
            - orchestration/concepts/flows.md
            - orchestration/concepts/projects.md
            - orchestration/concepts/kv_store.md
            - orchestration/concepts/secrets.md
            - orchestration/concepts/automations.md
            - orchestration/concepts/cloud_hooks.md
            - orchestration/concepts/services.md
            - orchestration/concepts/artifacts.md
        - Flow Configuration:
            - orchestration/flow_config/overview.md
            - orchestration/flow_config/storage.md
            - orchestration/flow_config/run_configs.md
            - orchestration/flow_config/executors.md
            - orchestration/flow_config/docker.md
        - Flow Runs:
            - orchestration/flow-runs/overview.md
            - orchestration/flow-runs/creation.md
            - orchestration/flow-runs/inspection.md
            - orchestration/flow-runs/task-runs.md
            - orchestration/flow-runs/scheduling.md
            - orchestration/flow-runs/setting-states.md
            - orchestration/flow-runs/concurrency-limits.md
        - Agents:
            - orchestration/agents/overview.md
            - orchestration/agents/local.md
            - orchestration/agents/docker.md
            - orchestration/agents/kubernetes.md
            - orchestration/agents/vertex.md
            - orchestration/agents/ecs.md
        - UI:
            - orchestration/ui/dashboard.md
            - orchestration/ui/flow.md
            - orchestration/ui/flow-run.md
            - orchestration/ui/task-run.md
            - orchestration/ui/automations.md
            - orchestration/ui/interactive-api.md
            - orchestration/ui/team-settings.md
        - Role-Based Access Controls: orchestration/rbac/overview.md
        - Server:
            - orchestration/server/overview.md
            - orchestration/server/architecture.md
            - orchestration/server/deploy-local.md
            - orchestration/server/telemetry.md
            - orchestration/server/troubleshooting.md
        - Deployment Recipes:
            - orchestration/recipes/third_party_auth.md
            - orchestration/recipes/configuring_storage.md
            - orchestration/recipes/multi_flow_storage.md
            - orchestration/recipes/k8s_dask.md
            - orchestration/recipes/k8s_docker_sidecar.md
        - Integrations:
            - orchestration/integrations/pagerduty.md
        - FAQ:
            - orchestration/faq/config.md
            - orchestration/faq/dataflow.md
            - orchestration/faq/debug.md
            - orchestration/faq/faq.md
            - orchestration/faq/upgrade_environments.md
            - orchestration/faq/upgrading_1.0.md
        - Legacy Environments:
            - orchestration/execution/overview.md
            - orchestration/execution/storage_options.md
            - orchestration/execution/local_environment.md
            - orchestration/execution/dask_cloud_provider_environment.md
            - orchestration/execution/dask_k8s_environment.md
            - orchestration/execution/k8s_job_environment.md
            - orchestration/execution/fargate_task_environment.md
            - orchestration/execution/custom_environment.md
    - Task Library:
        - Overview: core/task_library/overview.md
        - Contributing: core/task_library/contributing.md
    - API Reference: 
        - Overview: api-ref/latest/README.md
        - prefect.exceptions: api-ref/latest/exceptions.md
        - prefect.executors: api-ref/latest/executors.md
        - prefect.run_configs: api-ref/latest/run_configs.md
        - prefect.storage: api-ref/latest/storage.md
        - prefect.triggers: api-ref/latest/triggers.md
        - prefect.agent:
            - api-ref/latest/agent/agent.md
            - api-ref/latest/agent/ecs.md
            - api-ref/latest/agent/docker.md
            - api-ref/latest/agent/kubernetes.md
            - api-ref/latest/agent/local.md
            - api-ref/latest/agent/vertex.md
        - prefect.backend:
            - api-ref/latest/backend/artifacts.md
            - api-ref/latest/backend/flow.md
            - api-ref/latest/backend/flow_run.md
            - api-ref/latest/backend/kv_store.md
            - api-ref/latest/backend/task_run.md
            - api-ref/latest/backend/tenant.md
        - prefect.cli:
            - api-ref/latest/cli/agent.md
            - api-ref/latest/cli/get.md
            - api-ref/latest/cli/kv_store.md
            - api-ref/latest/cli/register.md
            - api-ref/latest/cli/create.md
            - api-ref/latest/cli/auth.md
            - api-ref/latest/cli/describe.md
            - api-ref/latest/cli/build.md
            - api-ref/latest/cli/delete.md
            - api-ref/latest/cli/server.md
            - api-ref/latest/cli/run.md
        - prefect.client:
            - api-ref/latest/client/client.md
            - api-ref/latest/client/secrets.md
        - prefect.core:
            - api-ref/latest/core/edge.md
            - api-ref/latest/core/flow.md
            - api-ref/latest/core/parameters.md
            - api-ref/latest/core/task.md
        - prefect.engine:
            - api-ref/latest/engine/cache_validators.md
            - api-ref/latest/engine/cloud.md
            - api-ref/latest/engine/flow_runner.md
            - api-ref/latest/engine/result.md
            - api-ref/latest/engine/results.md
            - api-ref/latest/engine/serializers.md
            - api-ref/latest/engine/signals.md
            - api-ref/latest/engine/state.md
            - api-ref/latest/engine/task_runner.md
        - prefect.schedules:
            - api-ref/latest/schedules/adjustments.md
            - api-ref/latest/schedules/clocks.md
            - api-ref/latest/schedules/filters.md
            - api-ref/latest/schedules/schedules.md
        - prefect.tasks:
            - api-ref/latest/tasks/airbyte.md
            - api-ref/latest/tasks/airtable.md
            - api-ref/latest/tasks/asana.md
            - api-ref/latest/tasks/aws.md
            - api-ref/latest/tasks/azure.md
            - api-ref/latest/tasks/azureml.md
            - api-ref/latest/tasks/census.md
            - api-ref/latest/tasks/collections.md
            - api-ref/latest/tasks/constants.md
            - api-ref/latest/tasks/control_flow.md
            - api-ref/latest/tasks/cubejs.md
            - api-ref/latest/tasks/databricks.md
            - api-ref/latest/tasks/dbt.md
            - api-ref/latest/tasks/docker.md
            - api-ref/latest/tasks/dremio.md
            - api-ref/latest/tasks/dropbox.md
            - api-ref/latest/tasks/exasol.md
            - api-ref/latest/tasks/files.md
            - api-ref/latest/tasks/firebolt.md
            - api-ref/latest/tasks/fivetran.md
            - api-ref/latest/tasks/function.md
            - api-ref/latest/tasks/gcp.md
            - api-ref/latest/tasks/github.md
            - api-ref/latest/tasks/great_expectations.md
            - api-ref/latest/tasks/gsheets.md
            - api-ref/latest/tasks/Hightouch.md
            - api-ref/latest/tasks/jira.md
            - api-ref/latest/tasks/jupyter.md
            - api-ref/latest/tasks/kafka.md
            - api-ref/latest/tasks/kubernetes.md
            - api-ref/latest/tasks/mixpanel.md
            - api-ref/latest/tasks/monday.md
            - api-ref/latest/tasks/monte_carlo.md
            - api-ref/latest/tasks/mysql.md
            - api-ref/latest/tasks/Neo4j.md
            - api-ref/latest/tasks/notifications.md
            - api-ref/latest/tasks/operators.md
            - api-ref/latest/tasks/postgres.md
            - api-ref/latest/tasks/prefect.md
            - api-ref/latest/tasks/prometheus.md
            - api-ref/latest/tasks/redis.md
            - api-ref/latest/tasks/resources.md
            - api-ref/latest/tasks/rss.md
            - api-ref/latest/tasks/secrets.md
            - api-ref/latest/tasks/sendgrid.md
            - api-ref/latest/tasks/sftp.md
            - api-ref/latest/tasks/shell.md
            - api-ref/latest/tasks/snowflake.md
            - api-ref/latest/tasks/sodaspark.md
            - api-ref/latest/tasks/sodasql.md
            - api-ref/latest/tasks/spacy.md
            - api-ref/latest/tasks/sql_server.md
            - api-ref/latest/tasks/sqlite.md
            - api-ref/latest/tasks/strings.md
            - api-ref/latest/tasks/toloka.md
            - api-ref/latest/tasks/Transform.md
            - api-ref/latest/tasks/trello.md
            - api-ref/latest/tasks/twitter.md
            - api-ref/latest/tasks/zendesk.md
        - prefect.utilities:
            - api-ref/latest/utilities/collections.md
            - api-ref/latest/utilities/configuration.md
            - api-ref/latest/utilities/context.md
            - api-ref/latest/utilities/debug.md
            - api-ref/latest/utilities/diagnostics.md
            - api-ref/latest/utilities/edges.md
            - api-ref/latest/utilities/executors.md
            - api-ref/latest/utilities/gcp.md
            - api-ref/latest/utilities/graphql.md
            - api-ref/latest/utilities/logging.md
            - api-ref/latest/utilities/notifications.md
            - api-ref/latest/utilities/serialization.md
            - api-ref/latest/utilities/tasks.md
        - Changelog: api-ref/latest/changelog.md