site_name: Prefect 1.0
site_url: https://docs.prefect.io
repo_url: https://github.com/PrefectHQ/prefect
edit_uri:
extra_css:
    - stylesheets/theme.css
    - stylesheets/admonitions.css
    - stylesheets/api_ref.css
    - stylesheets/rest_ref.css
    - stylesheets/syntax_highlights.css
    - stylesheets/termynal.css
    - stylesheets/extra.css
extra_javascript:
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
theme:
    name: material
    custom_dir: overrides
    favicon: /img/favicon.ico
    features:
        - toc.integrate
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.instant
    font:
        text: Inter
        code: Source Code Pro
    icon:
        repo: fontawesome/brands/github
    logo: img/assets/logomark-light.svg
    palette:
        primary: blue
        accent: blue
    custom_dir: docs/overrides
plugins:
    autorefs: {}
    mkdocstrings:
        custom_templates: docs/templates
        handlers:
            python:
                rendering:
                    show_root_heading: True
                    show_object_full_path: False
                    show_category_heading: False
                    show_bases: False
                    heading_level: 1
        watch:
            - src/prefect/
    search: {}
nav:
    - Prefect 1.0: index.md
    - Core:
        - Overview: core/README.md
        - About Prefect:
            - Why Prefect?: core/about_prefect/why-prefect.md
            - Why not Airflow?: core/about_prefect/why-not-airflow.md
            - Thinking Prefectly: core/about_prefect/thinking-prefectly.md
            - Next Steps: core/about_prefect/next-steps.md
        - Getting Started:
            - core/getting_started/quick-start.md
            - core/getting_started/install.md
            - core/getting_started/basic-core-flow.md
            - core/getting_started/more-resources.md
        - ETL Tutorial:
            - core/tutorial/01-etl-before-prefect.md
            - core/tutorial/02-etl-flow.md
            - core/tutorial/03-parameterized-flow.md
            - core/tutorial/04-handling-failure.md
            - core/tutorial/05-running-on-a-schedule.md
            - core/tutorial/06-parallel-execution.md
            - core/tutorial/07-next-steps.md
        - Core Concepts: 
            - core/concepts/tasks.md
            - core/concepts/flows.md
            - core/concepts/parameters.md
            - core/concepts/states.md
            - core/concepts/engine.md
            - core/concepts/execution.md
            - core/concepts/logging.md
            - core/concepts/mapping.md
            - core/concepts/notifications.md
            - core/concepts/persistence.md
            - core/concepts/results.md
            - core/concepts/templating.md
            - core/concepts/schedules.md
            - core/concepts/secrets.md
            - core/concepts/configuration.md
            - core/concepts/best-practices.md
            - core/concepts/common-pitfalls.md
        - Advanced Tutorials:
            - Contents: core/advanced_tutorials/README.md
            - core/advanced_tutorials/advanced-mapping.md
            - core/advanced_tutorials/calculator.md
            - core/advanced_tutorials/custom-logs.md
            - core/advanced_tutorials/dask-cluster.md
            - core/advanced_tutorials/etl.md
            - core/advanced_tutorials/local-debugging.md
            - core/advanced_tutorials/slack-notifications.md
            - core/advanced_tutorials/task-guide.md
            - core/advanced_tutorials/task-looping.md
            - core/advanced_tutorials/using-results.md
            - core/advanced_tutorials/visualization.md
        - Examples:
            - core/examples/overview.md
            - core/examples/parameters.md
            - core/examples/conditional.md
            - core/examples/mapping.md
        - PINs:
            - Contents: core/PINs/README.md
            - core/PINs/PIN-01-Introduce-PINs.md
            - core/PINs/PIN-02-Result-Handlers.md
            - core/PINs/PIN-03-Agent-Environment.md
            - core/PINs/PIN-04-Result-Objects.md
            - core/PINs/PIN-05-Combining-Tasks.md
            - core/PINs/PIN-06-Remove-Constant-Tasks.md
            - core/PINs/PIN-07-Storage-Execution.md
            - core/PINs/PIN-08-Listener-Flows.md
            - core/PINs/PIN-09-CLI.md
            - core/PINs/PIN-10-Schedules.md
            - core/PINs/PIN-11-Task-Loops.md
            - core/PINs/PIN-12-Environment-Callbacks.md
            - core/PINs/PIN-13-Universal-Deploy.md
            - core/PINs/PIN-14-Listener-Flows-2.md
            - core/PINs/PIN-15-Skip-as-Finished-and-Conditionals.md
            - core/PINs/PIN-16-Results-and-Targets.md
        - Development:
            - core/development/overview.md
            - core/development/style.md
            - core/development/documentation.md
            - core/development/tests.md
            - core/development/contributing.md
            - core/development/release-checklist.md
            - core/development/sprints.md
        - Idioms:
            - Overview: core/idioms/idioms.md
            - core/idioms/notifications.md
            - core/idioms/secrets.md
            - core/idioms/script-based.md
            - core/idioms/testing-flows.md
            - core/idioms/task-run-names.md
            - core/idioms/conditional.md
            - core/idioms/mapping.md
            - core/idioms/parallel.md
            - core/idioms/targets.md
            - core/idioms/logging.md
            - core/idioms/flow-to-flow.md
            - core/idioms/resource-manager.md
            - core/idioms/piping.md
            - core/idioms/task-results.md
            - core/idioms/pause-for-approval.md
        - FAQ: core/faq.md
        - core/community.md
        - core/code_of_conduct.md
    - Orchestration: 
        - Overview: orchestration/README.md

    - Task Library:
        - Overview: core/task_library/overview.md
        - Contributing: core/task_library/contributing.md